name: Firebase Deploy to Staging Environment

on:
  push:
    branches: 
    - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run build
      - run: npm install -g gatsby-cli@4.17.1
      - run: gatsby build
      - run: ls -la public
      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_STAGING }}
